# Ejemplo de uso de Google Colab 😍😍
Este documento es un ejemplo de uso de Google Colab

## Importaciones de librerías

In [43]:
import pandas as pd

## Obtención del **fichero de datos**

In [44]:
URL_DATA_FILE = 'https://fpaniaguapython.github.io/datos/sanblas202609.csv'
df_original = pd.read_csv(URL_DATA_FILE)
df_original

,Marca temporal,Nombre y apellidos,Año de nacimiento,Altura,Peso,Localidad,Número de hijos
0,2026/09/07 8:32:44 p. m. EEST,Batman,1971,170,85,Alcorcón,0
1,2026/09/07 8:32:49 p. m. EEST,Pepe Roberto,1989,"1,98",120,Colmenar Viejo,0
2,2026/09/07 8:33:12 p. m. EEST,Belén Bonilla,1977,160,60,Arganda del Rey,1000
3,2026/09/07 8:33:20 p. m. EEST,Luis Martínez Solar,10/10/2000,NaN,40,Madrid,2
4,2026/09/07 8:33:32 p. m. EEST,Perry Mason,1972,170,65,Madrid,2
5,2026/09/07 8:33:33 p. m. EEST,Pedro Sanchez,1945,190,90,Arganda del Rey,3
6,2026/09/07 8:33:45 p. m. EEST,Cipriano guapo,1999,"1,35",100,Madrid,1
7,2026/09/07 8:33:47 p. m. EEST,Juan,1962,165,50 kg,Madrid,0
8,2026/09/07 8:34:10 p. m. EEST,Antonio Perez Martinez,07/04/2030,1.70,78,Madrid,0.0
9,2026/09/07 8:34:25 p. m. EEST,Pedro Sánchez,1970,1.82,84,Colmenar Viejo,1
10,2026/09/07 8:34:28 p. m. EEST,Manolito Manos Tijeras,1995,"1,75",80,NaN,3
11,2026/09/07 8:34:45 p. m. EEST,Toni el Conde,No te interesa,198,Eso no se pregunta,Madrid,Ni lo se
12,2026/09/07 8:34:47 p. m. EEST,Sal Valentine,20/04/1999,3 metros,290 kg,Madrid,0
13,2026/09/07 8:34:48 p. m. EEST,Luz Casal,1979,"2,30",52,Torrejón de Ardoz,0
14,2026/09/07 8:34:53 p. m. EEST,Vanessa,NaN,156,-30,Torrejón de Ardoz,0
15,2026/09/07 8:35:29 p. m. EEST,Nikolai Marino,1989,2.15,256,Torrejón de Ardoz,12

Creo una copia del df_original para trabajar con ella y tener siempre disponible el df_original

In [45]:
df_trabajo = df_original.copy()

Sustituir de los nombres de columnas por otros más sencillos

In [46]:
df_trabajo.columns = df_trabajo.columns.str.replace(' ', '_').str.lower()
df_trabajo.head() # Muestra los (por defecto) 5 primeros registros

,marca_temporal,nombre_y_apellidos,año_de_nacimiento,altura,peso,localidad,número_de_hijos
0,2026/09/07 8:32:44 p. m. EEST,Batman,1971,170,85,Alcorcón,0
1,2026/09/07 8:32:49 p. m. EEST,Pepe Roberto,1989,"1,98",120,Colmenar Viejo,0
2,2026/09/07 8:33:12 p. m. EEST,Belén Bonilla,1977,160,60,Arganda del Rey,1000
3,2026/09/07 8:33:20 p. m. EEST,Luis Martínez Solar,10/10/2000,NaN,40,Madrid,2
4,2026/09/07 8:33:32 p. m. EEST,Perry Mason,1972,170,65,Madrid,2

## Anonimizar la serie

In [47]:
df_trabajo['nombre_y_apellidos']='Anónimo'
df_trabajo.head()

,marca_temporal,nombre_y_apellidos,año_de_nacimiento,altura,peso,localidad,número_de_hijos
0,2026/09/07 8:32:44 p. m. EEST,Anónimo,1971,170,85,Alcorcón,0
1,2026/09/07 8:32:49 p. m. EEST,Anónimo,1989,"1,98",120,Colmenar Viejo,0
2,2026/09/07 8:33:12 p. m. EEST,Anónimo,1977,160,60,Arganda del Rey,1000
3,2026/09/07 8:33:20 p. m. EEST,Anónimo,10/10/2000,NaN,40,Madrid,2
4,2026/09/07 8:33:32 p. m. EEST,Anónimo,1972,170,65,Madrid,2