In [180]:
import pandas as pd

datos = {
    "Alumno": ["Ana", "Luis", "Marta", "Carlos", "Sofía"],
    "Matemáticas": [8, None, 4, 7, 10],
    "Lengua extranjera": [7, 8, 9, None, 9],
    "Inglés": [9, 7, 8, 8, 10],
    "Historia": [5, 9, 7, 8, 9],
    "Física": [8, 10, 10, 7, 8]
}

df = pd.DataFrame(datos)

display(df)
display(df.columns)
display(df.index)
display(df)

   Alumno  Matemáticas  Lengua extranjera  Inglés  Historia  Física
0     Ana          8.0                7.0       9         5       8
1    Luis          NaN                8.0       7         9      10
2   Marta          4.0                9.0       8         7      10
3  Carlos          7.0                NaN       8         8       7
4   Sofía         10.0                9.0      10         9       8

Index(['Alumno', 'Matemáticas', 'Lengua extranjera', 'Inglés', 'Historia',
       'Física'],
      dtype='object')

RangeIndex(start=0, stop=5, step=1)

   Alumno  Matemáticas  Lengua extranjera  Inglés  Historia  Física
0     Ana          8.0                7.0       9         5       8
1    Luis          NaN                8.0       7         9      10
2   Marta          4.0                9.0       8         7      10
3  Carlos          7.0                NaN       8         8       7
4   Sofía         10.0                9.0      10         9       8

In [181]:
# Cambiamos los nombres de las columnas
df.columns = df.columns.str.lower().str.replace(' ','_')
display(df.head())

   alumno  matemáticas  lengua_extranjera  inglés  historia  física
0     Ana          8.0                7.0       9         5       8
1    Luis          NaN                8.0       7         9      10
2   Marta          4.0                9.0       8         7      10
3  Carlos          7.0                NaN       8         8       7
4   Sofía         10.0                9.0      10         9       8

In [182]:
# Cambiar el índice por el nombre de los alumnos
#df.index = df['alumno']
df.set_index(df['alumno'], inplace=True)
display(df.head())

        alumno  matemáticas  lengua_extranjera  inglés  historia  física
alumno
Ana        Ana          8.0                7.0       9         5       8
Luis      Luis          NaN                8.0       7         9      10
Marta    Marta          4.0                9.0       8         7      10
Carlos  Carlos          7.0                NaN       8         8       7
Sofía    Sofía         10.0                9.0      10         9       8

In [183]:
# Eliminar la columna alumno
df.drop('alumno', axis=1, inplace=True)

display(df.head())

        matemáticas  lengua_extranjera  inglés  historia  física
alumno
Ana             8.0                7.0       9         5       8
Luis            NaN                8.0       7         9      10
Marta           4.0                9.0       8         7      10
Carlos          7.0                NaN       8         8       7
Sofía          10.0                9.0      10         9       8

In [184]:
#df.dropna(axis=1, inplace=True) # Nos cargamos la columna que tiene NaN
#df.dropna(axis=0, inplace=True) # Nos cargamos la columna que tiene NaN
#display(df.head())

In [185]:
# Rellenar los NaN con la media de cada alumno
# La T obtiene la matriz transpuesta (intercambia filas por columnas)
# --> Necesario para que pueda calcular la media sobre las filas originales
df = df.T.fillna(df.mean(axis=1)).T
display(df.head())

        matemáticas  lengua_extranjera  inglés  historia  física
alumno
Ana             8.0                7.0     9.0       5.0     8.0
Luis            8.5                8.0     7.0       9.0    10.0
Marta           4.0                9.0     8.0       7.0    10.0
Carlos          7.0                7.5     8.0       8.0     7.0
Sofía          10.0                9.0    10.0       9.0     8.0